# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.2.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.0.0"
wally = "UpliftGames/wally@0.3.1"
stylua = "JohnnyMorganz/stylua@0.14.0"
selene = "Kampfkarren/selene@0.18.2"
remodel = "rojo-rbx/remodel@0.10.0"